.github/workflows/build.yaml
Dockerfile
build/composer.sh
build/golang.sh
build/gradle.sh
build/install-tool.sh
build/java.sh
build/node.sh
build/npm.sh
build/php.sh
build/pnpm.sh
build/util.sh
build/yarn.sh
builder.json
docker/entrypoint.sh

Would allow writing
```Dockerfile
FROM renovate/buildpack
ARG NODE_VERSION=12
RUN install-tool node
```

feat: add install wrapper

---

.github/workflows/build.yaml
bin/install-pip
bin/install-tool
build/docker.sh
build/golang.sh
build/poetry.sh
build/python.sh
build/ruby.sh
build/util.sh
renovate.json
test/cocoapods/Dockerfile
test/golang/Dockerfile
test/golang/test/a/go.mod
test/golang/test/a/go.sum
test/golang/test/b/go.mod
test/golang/test/b/go.sum
test/golang/test/c/go.mod
test/pipenv/Dockerfile
test/pipenv/test/a/Pipfile
test/pipenv/test/a/Pipfile.lock
test/poetry/Dockerfile
test/poetry/test/a/poetry.lock
test/poetry/test/a/pyproject.toml
test/poetry/test/b/poetry.lock
test/poetry/test/b/pyproject.toml

- refactor scripts
- add tools
- add tests
- fixes

feat: refactor tools

---

.github/workflows/build.yaml
Dockerfile
bin/docker-entrypoint.sh
build/elixir.sh
build/util.sh
docker/entrypoint.sh
test/mix/Dockerfile

* install hex and rebar
* simplify env

feat: optimizations

---

bin/docker-entrypoint.sh

Correctly handle arguments in entrypoint

---

.github/workflows/build.yaml
bin/docker-entrypoint.sh
build/node.sh
build/util.sh
test/node/Dockerfile

* use `$BASH_ENV`
* add node wrapper (backward compatibility)
ref: renovatebot/docker-renovate#12

feat: optimizations and compatibility

---

build/python.sh
test/pipenv/Dockerfile

ref: renovatebot/renovate#6036

fix: wrong pyenv wrapper

---

src/python/build/python.sh
test/pipenv/Dockerfile

* use prebuild python if exists
* skip install if found
* fall back to source install

feat(python): use prebuild python

---

.github/auto-cancel-actions.yml
.github/workflows/build.yaml

The `auto-cancel-actions` app needs to be enabled before!

chore: remove cancel action

---

src/python/build/python.sh
test/pipenv/Dockerfile
test/poetry/Dockerfile

fix(python): add missing build deps

---

src/node/build/node.sh
test/node/Dockerfile

feat(node): redirect npm prefix

---

src/node/build/node.sh
test/node/Dockerfile

fix(node): wrong global install path

---

.github/workflows/build.yaml
Dockerfile
builder.json

**changes**
* builds for `18.04` and `20.04`
* tags `18.04` as latest
**tag samples**
* latest, 2, 2-18.04: buildpack full
* 2-node, 2-node-18.04: buildpack node
* 2-20.04: buildpack full
* 2-node-20.04: buildpack node

feat: add ubuntu flavor

---

.github/workflows/build.yaml
Dockerfile
src/rust/build/rust.sh
test/rust/Dockerfile

blocks https://github.com/renovatebot/docker-rust/pull/7

fix(rust): missing tool chain

---

Dockerfile
README.md

* add version to image
* update readme

feat: improvements

---

src/rust/build/rust.sh
test/rust/Dockerfile

feat(rust): use standalone installer

---

src/golang/build/golang.sh
test/golang/Dockerfile

fix(golang): fix wrong file name

---

.github/workflows/build.yaml
Dockerfile
src/swift/build/swift.sh
test/swift/Dockerfile
test/swift/test/a/Package.resolved
test/swift/test/a/Package.swift
test/swift/test/b/Package.resolved
test/swift/test/b/Package.swift
test/swift/test/c/Package.resolved
test/swift/test/c/Package.swift

closes #50 
ref renovatebot/renovate#6924

feat: add swift

---

.github/workflows/build.yaml
Dockerfile
src/helm/build/helm.sh
test/helm/Dockerfile

feat: add helm

---

.github/workflows/build.yaml
src/erlang/build/erlang.sh
test/erlang/Dockerfile

Should fix recent build failures
https://www.erlang-solutions.com/resources/download.html#product-instruction

feat: update erlang installer

---

.github/workflows/build.yaml
.prettierrc
Dockerfile
src/dotnet/build/dotnet.sh
src/php/build/php.sh
test/erlang/Dockerfile

- simplify build
- test all flavors
- fix focal build issues

feat: focal compatibility

---

.github/workflows/build.yaml
Dockerfile
src/powershell/build/powershell.sh
test/powershell/Dockerfile

Added PowerShell definition.
The open question I have is around `libicu`. PowerShell requires an ICU library to be installed, otherwise you need to set the environment variable `DOTNET_SYSTEM_GLOBALIZATION_INVARIANT` to `1`.
The workaround I have currently, is adding the `libicu-dev` package, as on bionic the package is called `libicu60`, whereas on focal it's `libicu66`.
My question is: are we able to set the `DOTNET_SYSTEM_GLOBALIZATION_INVARIANT` environment variable in the `docker-powershell` repository? And should I just set it manually in the tests cases for now? Or do we want the `libicu` package installed?
Closes #77

feat(powershell): add powershell container

---

src/base/bin/install-tool
src/base/build/util.sh

This allows tool to have a dash in name.
/cc @JamieMagee

fix: escape export

---

src/ruby/build/ruby.sh
test/ruby/Dockerfile

This add 312kB files and fixes recently failing cocoapods tests

fix(ruby): add cocoapods libffi-dev dep

---

renovate.json
src/erlang/build/erlang.sh
test/erlang/Dockerfile

Add version wildcard, so we do not need to know the full debian version

feat(erlang): allow auto update

---

renovate.json
test/erlang/Dockerfile

chore(renovate): use erlang github release

---

test/erlang/Dockerfile

fix: disable erlang updates

---

Dockerfile

regression of #82
/cc @JamieMagee 😉

fix: wrong path

---

src/rust/build/rust.sh

closes renovatebot/renovate#8478

fix(rust): add missing cargo home

---

src/python/bin/install-pip
src/python/build/pip.sh
src/python/build/poetry.sh
src/python/build/python.sh
test/python/Dockerfile
test/python/test/f/requirements.txt

No longer set `PIP_USER=yes`.
It's no longer required by pip as ist installing as user automatically asn we have latest pip in all python images.
fixes renovatebot/renovate#8547

fix(python): do not set PIP_USER

---

src/python/buildpack/tools/poetry.sh
test/python/Dockerfile

- add poetry executable bit for all
- update tests to catch that
fixes #150

fix(poetry): add missing executable bit

---

src/dotnet/buildpack/tools/dotnet.sh
src/erlang/buildpack/tools/elixir.sh
src/golang/buildpack/tools/golang.sh
src/helm/buildpack/tools/helm.sh
src/java/buildpack/tools/gradle.sh
src/node/buildpack/tools/node.sh
src/node/buildpack/tools/npm.sh
src/node/buildpack/tools/pnpm.sh
src/node/buildpack/tools/yarn.sh
src/powershell/buildpack/tools/powershell.sh
src/python/buildpack/tools/poetry.sh
src/python/buildpack/tools/python.sh
src/ruby/buildpack/tools/ruby.sh
src/rust/buildpack/tools/rust.sh
src/swift/buildpack/tools/swift.sh
test/dotnet/Dockerfile
test/golang/Dockerfile
test/helm/Dockerfile
test/java/Dockerfile
test/node/Dockerfile
test/powershell/Dockerfile
test/python/Dockerfile
test/ruby/Dockerfile
test/rust/Dockerfile
test/swift/Dockerfile

not needed (needs refactoring):
- java
- erlang
- docker
- php
- composer
ref #163

feat: add global wrapper

---

src/base/buildpack/tools/git.sh
src/php/buildpack/tools/php.sh

Use curl to download gpg key to support proxy settings.

fix: use curl to fetch gpg key

---

.github/workflows/build.yaml
Dockerfile
src/nix/buildpack/tools/nix.sh
test/nix/Dockerfile

Not 100% if the nix builder users are required, but including for now
Inspired by:
- https://github.com/NixOS/docker
- https://github.com/cachix/install-nix-action
Closes #80

feat: add nix dockerfile

---

.github/auto-cancel-actions.yml
.github/workflows/build.yaml
Dockerfile

- renovatebot/docker-renovate#235

fix: add weekly cache buster

---

renovate.json

fix: let git trigger a patch release

---

renovate.json

- https://github.com/containerbase/buildpack/pull/189

chore: update config

---

.github/workflows/build.yaml

See https://github.com/renovatebot/docker-renovate/pull/244

fix: explicitly set GITHUB_TOKEN permissions

---

.github/workflows/build.yaml
Dockerfile
test/Dockerfile.bionic

- remove obsolete language stages
- pass `CACHE_WEEK`
- use base image for distro tests
- unpin `bionic` to use precached image for tests

test: simplify tests

---

test/java/Dockerfile

Checking why java tests are failing without change

test: java testing
